import type { ElegantRouterOption } from '@elegant-router/core';

export interface ElegantVueRouterOption extends ElegantRouterOption {
  /**
   * the declaration file directory of the generated routes
   * @default 'src/typings/elegant-router.d.ts'
   */
  dtsDir: string;
  /**
   * the directory of the imports of routes
   * @default 'src/router/auto-imports.ts'
   */
  importsDir: string;
  /**
   * whether the route is lazy import
   * @param routeName route name
   * @default _name => true
   * @example
   * - the direct import
   * ```ts
   * import Home from './views/home/index.vue';
   * ```
   * - the lazy import
   * ```ts
   * const Home = import('./views/home/index.vue');
   * ```
   */
  lazyImport(routeName: string): boolean;
  /**
   * the directory of the route const
   * @default 'src/router/auto-routes.ts'
   */
  constDir: string;
  /**
   * whether the route is split to modules
   * @default false
   * @example
   * - true
   *  `route page "about", will generate the route const module "/modules/about.ts" in the router directory`
   * - false
   * `route page "about", will generate or update the route const in the route const directory
   */
  splitModule: boolean;
  /**
   * the module directory of the generated routes
   * @default "src/router/modules"
   */
  moduleDir: string;
  /**
   * define custom routes, which's route imports and route const will not be generated by the plugin
   * @description the name path map of custom route
   * @default
   * ```ts
   *  const routesMap: Record<string, string> = {
   *    root: '/', // the root route
   *    notFound: '/:pathMatch(.*)*' // the 404 route
   * }
   * ```
   */
  customRoutesMap: Record<string, string>;
  /**
   * the name and file path of the route layouts
   * @default
   * ```ts
   * const layouts: Record<string, string> = {
   *   default: 'src/layouts/default-layout/index.vue'
   * }
   * ```
   */
  layouts: Record<string, string>;
  /**
   * the default layout name
   * @description if it doesn't set, it will be the first key of option "layouts"
   */
  defaultLayout: string;
  /**
   * the route meta generator
   * @param routeName the route name
   */
  onRouteMetaGen(routeName: string): Record<string, unknown>;
}
