import type { ElegantRouterOption } from '@elegant-router/core';

export interface ElegantVueRouterOption extends ElegantRouterOption {
  /**
   * the declaration file directory of the generated routes
   * @default 'src/typings/elegant-router.d.ts'
   */
  dtsDir: string;
  /**
   * the directory of the imports of routes
   * @default 'src/router/auto-imports.ts'
   */
  importsDir: string;
  /**
   * whether the route is lazy import
   * @param name route name
   * @default _name => true
   * @example
   * - the direct import
   * ```ts
   * import Home from './views/home/index.vue';
   * ```
   * - the lazy import
   * ```ts
   * const Home = import('./views/home/index.vue');
   * ```
   */
  lazyImport(name: string): boolean;
  /**
   * the directory of the route const
   * @default 'src/router/auto-routes.ts'
   */
  constDir: string;
  /**
   * whether the route is split to modules
   * @default true
   * @example
   * - true
   *  `route page "about", will generate the route const module "/modules/about.ts" in the router directory`
   * - false
   * `route page "about", will generate or update the route const in the route const directory
   */
  splitModule: boolean;
  /**
   * the module directory of the generated routes
   * @default "src/router/modules"
   */
  moduleDir: string;
  /**
   * define custom routes, which will not be generated by the plugin
   * @description the custom route name collection
   */
  customConstRoutes: string[];
}
