/* eslint-disable */
/* prettier-ignore */
// Generated by elegent-router
// Read more: https://github.com/soybeanjs/elegent-router

declare module "@elegent-router/types" {
  /**
   * the root route key
   */
  export type RootRouteKey = "root";

  /**
   * the root path
   */
  export type RootRoutePath = "/";

  /**
   * the not found route, which catch the invalid route path
   */
  export type NotFoundRouteKey = "not-found";

  /**
   * the not found route path, which catch the invalid route path
   */
  export type NotFoundRoutePath = "/:pathMatch(.*)*";

  /**
   * route map
   */
  export type RouteMap = {
    "root": "/";
    "not-found": "/:pathMatch(.*)*";
    "demo-a": "/demo-a";
    "demo-a_child1": "/demo-a/child1";
    "demo-a_child2": "/demo-a/child2";
    "demo-a_child2_child3": "/demo-a/child2/child3";
    "demo-a_child3": "/demo-a/child3";
    "demo3": "/demo3/:id";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RouteMap;

  /**
   * the last level route, which has the page file
   */
  export type LastLevelRoute = Extract<
    RouteKey,
    | "demo-a_child1"
    | "demo-a_child2_child3"
    | "demo-a_child3"
    | "demo3"
  >;
}
