/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

declare module "@elegant-router/types" {
  /**
   * route map
   */
  export type RouteMap = {
    "root": "/";
    "notFound": "/:pathMatch(.*)*";
    "403": "/403";
    "demo-a": "/demo-a";
    "demo-a_child1": "/demo-a/child1";
    "demo-a_child2": "/demo-a/child2";
    "demo-a_child2_child3": "/demo-a/child2/child3";
    "demo-a_child3": "/demo-a/child3";
    "demo3": "/demo3/:id";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RouteMap;

  /**
   * custom route key
   */ 
  export type CustomRouteKey = Extract<
    RouteKey,
    | "root"
    | "notFound"
  >;
  
  /**
   * the last level route, which has the page file
   */
  export type LastLevelRoute = Extract<
    RouteKey,
    | "403"
    | "demo-a_child1"
    | "demo-a_child2_child3"
    | "demo-a_child3"
    | "demo3"
  >;
}
