/**
 * create the prefix comment of the generated file
 * @param disabledFormat whether disabled format
 */
export function createPrefixCommentOfGenFile(disabledFormat = true) {
  const prefix = `/* eslint-disable */
/* prettier-ignore */
`;
  let comment = `// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router`;

  if (disabledFormat) {
    comment = prefix + comment;
  }

  return comment;
}
