/* eslint-disable */
/* prettier-ignore */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

declare module "@elegant-router/types" {
  type RouteRecordSingleView = import("vue-router").RouteRecordSingleView;
  type RouteRecordRedirect = import("vue-router").RouteRecordRedirect;
  type RouteComponent = import("vue-router").RouteComponent;

  type Lazy<T> = () => Promise<T>;

  export type RawRouteComponent = RouteComponent | Lazy<RouteComponent>;

  /**
   * route layout key
   */
  export type RouteLayoutKey = "base" | "blank";

  /**
   * route path map
   */
  export type RoutePathMap = {
    "Root": "/";
    "NotFound": "/:pathMatch(.*)*";
    "403": "/403";
    "404": "/404";
    "Demo": "/demo";
    "Home": "/home";
    "HomeChild": "/home/child";
    "HomeChild2": "/home/child2";
    "List": "/list";
    "ListAdd": "/list/add";
    "ListDetail2IdUserId": "/list/detail2-:id?-:userId?";
    "ListDetailIdUserId": "/list/detail/:id/:userId";
    "ListEditId": "/list/edit/:id";
    "ListId": "/list/:id";
    "Login": "/login";
    "Reuse1": "/reuse1";
    "Reuse2Id": "/reuse2/:id";
    "Reuse3Id": "/reuse3/:id?";
    "Reuse4IdName": "/reuse4/:id?/:name?";
    "Wip": "/wip";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RoutePathMap;

  /**
   * route path
   */
  export type RoutePath = RoutePathMap[RouteKey];

  /**
   * root route key
   */
  export type RootRouteKey = 'Root';

  /**
   * not found route key
   */
  export type NotFoundRouteKey = 'NotFound';

  /**
   * builtin route key
   */
  export type BuiltinRouteKey = RootRouteKey | NotFoundRouteKey;

  /**
   * reuse route key
   */
  export type ReuseRouteKey = Extract<
    RouteKey,
    | "Reuse1"
    | "Reuse2Id"
    | "Reuse3Id"
    | "Reuse4IdName"
  >;

  /**
   * the route file key, which has it's own file
   */
  export type RouteFileKey = Exclude<RouteKey, BuiltinRouteKey | ReuseRouteKey>;

  /**
   * mapped name and path
   */
  type MappedNamePath = {
    [K in RouteKey]: { name: K; path: RoutePathMap[K] };
  }[RouteKey];

  /**
   * auto router single view
   */
  export type AutoRouterSingleView = Omit<RouteRecordSingleView, 'component' | 'name' | 'path'> & {
    component: RouteFileKey;
    layout: RouteLayoutKey;
  } & MappedNamePath;

  /**
   * auto router redirect
   */
  export type AutoRouterRedirect = Omit<RouteRecordRedirect, 'children' | 'name' | 'path'> & MappedNamePath;

  /**
   * auto router route
   */
  export type AutoRouterRoute = AutoRouterSingleView | AutoRouterRedirect;
}
