/* eslint-disable */
// @ts-nocheck
/* prettier-ignore */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

declare module "@elegant-router/types" {
  /**
   * route layout key
   */
  export type RouteLayoutKey = "base";

  /**
   * route path map
   */
  export type RoutePathMap = {
    "403": "/403";
    "404": "/404";
    "Login": "/login";
    "HomeChild": "/home/child";
    "Home": "/home";
    "ListId": "/list/:id";
    "ListAdd": "/list/add";
    "ListDetail2IdUserId": "/list/detail2-:id?-:userId?";
    "ListDetailIdUserId": "/list/detail/:id/:userId";
    "ListEditId": "/list/edit/:id";
    "List": "/list";
    "Root": "/";
    "NotFound": "/:pathMatch(.*)*";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RoutePathMap;

  /**
   * route path
   */
  export type RoutePath = RoutePathMap[RouteKey];

  /**
   * custom route key
   */
  export type CustomRouteKey = Extract<
    RouteKey,
    | "Root"
    | "NotFound"
  >;

  /**
   * the route file key, which has it's own file
   */
  export type RouteFileKey = Exclude<RouteKey, CustomRouteKey>;
}
