/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/403/index.vue"),
  404: () => import("@/views/404/index.vue"),
  500: () => import("@/views/500/index.vue"),
  "demo-a_child1": () => import("@/views/demo-a/child1/index.vue"),
  "demo-a_child2_child3": () => import("@/views/demo-a/child2/child3/index.vue"),
  "demo-a_child3": () => import("@/views/demo-a/child3/index.vue"),
  demo3: () => import("@/views/demo3/[id].vue"),
  "multi-menu_first_child": () => import("@/views/multi-menu/first_child/index.vue"),
  "multi-menu_second_child_home": () => import("@/views/multi-menu/second_child_home/index.vue"),
};
