// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

// import type { ElegantRoute } from '@elegant-router/types';

export const autoRoutes = [
  {
    name: '403',
    path: '/403',
    component: 'layout.base$view.403',
    meta: {
      title: '403'
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.base$view.404',
    meta: {
      title: '404'
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.base$view.500',
    meta: {
      title: '500'
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about'
    }
  },
  {
    name: 'list',
    path: '/list',
    component: 'layout.base',
    meta: {
      title: 'list'
    },
    children: [
      {
        name: 'list_detail',
        path: '/list/detail',
        component: 'view.list_detail',
        meta: {
          title: 'list_detail'
        }
      },
      {
        name: 'list_home',
        path: '/list/home',
        component: 'view.list_home',
        meta: {
          title: 'list_home'
        }
      }
    ]
  },
  {
    name: 'multi-menu',
    path: '/multi-menu',
    component: 'layout.base',
    meta: {
      title: 'multi-menu'
    },
    children: [
      {
        name: 'multi-menu_first',
        path: '/multi-menu/first',
        meta: {
          title: 'multi-menu_first'
        },
        children: [
          {
            name: 'multi-menu_first_child',
            path: '/multi-menu/first/child',
            component: 'view.multi-menu_first_child',
            meta: {
              title: 'multi-menu_first_child'
            }
          }
        ]
      },
      {
        name: 'multi-menu_second',
        path: '/multi-menu/second',
        meta: {
          title: 'multi-menu_second'
        },
        children: [
          {
            name: 'multi-menu_second_child',
            path: '/multi-menu/second/child',
            meta: {
              title: 'multi-menu_second_child'
            },
            children: [
              {
                name: 'multi-menu_second_child_home',
                path: '/multi-menu/second/child/home',
                component: 'view.multi-menu_second_child_home',
                meta: {
                  title: 'multi-menu_second_child_home'
                }
              }
            ]
          }
        ]
      }
    ]
  },
  {
    name: 'user',
    path: '/user/:id',
    component: 'layout.base$view.user',
    props: true,
    meta: {
      title: 'user'
    }
  }
];
