// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { ElegantRoute } from '@elegant-router/types';

export const autoRoutes: ElegantRoute[] = [
  {
    path: '/403',
    component: 'layout.default',
    children: [
      {
        name: '403',
        path: '',
        component: 'view.403',
        meta: {
          title: '403'
        }
      }
    ]
  },
  {
    path: '/404',
    component: 'layout.default',
    children: [
      {
        name: '404',
        path: '',
        component: 'view.404',
        meta: {
          title: '404'
        }
      }
    ]
  },
  {
    path: '/500',
    component: 'layout.default',
    children: [
      {
        name: '500',
        path: '',
        component: 'view.500',
        meta: {
          title: '500'
        }
      }
    ]
  },
  {
    name: 'demo-a',
    path: '/demo-a',
    component: 'layout.default',
    redirect: {
      name: 'demo-a_child1'
    },
    meta: {
      title: 'demo-a'
    },
    children: [
      {
        name: 'demo-a_child1',
        path: '/demo-a/child1',
        component: 'view.demo-a_child1',
        meta: {
          title: 'demo-a_child1'
        }
      },
      {
        name: 'demo-a_child2',
        path: '/demo-a/child2',
        redirect: {
          name: 'demo-a_child2_child3'
        },
        meta: {
          title: 'demo-a_child2'
        }
      },
      {
        name: 'demo-a_child2_child3',
        path: '/demo-a/child2/child3',
        component: 'view.demo-a_child2_child3',
        meta: {
          title: 'demo-a_child2_child3'
        }
      },
      {
        name: 'demo-a_child3',
        path: '/demo-a/child3',
        component: 'view.demo-a_child3',
        meta: {
          title: 'demo-a_child3'
        }
      }
    ]
  },
  {
    path: '/demo3/:id',
    component: 'layout.default',
    children: [
      {
        name: 'demo3',
        path: '',
        component: 'view.demo3',
        meta: {
          title: 'demo3'
        }
      }
    ]
  }
];
