/* eslint-disable */
/* prettier-ignore */
// Generated by elegent-router
// Read more: https://github.com/soybeanjs/elegent-router


import type { RouteComponent } from "vue-router";
import type { LastLevelRoute } from "@elegent-router/types";

export const views: Record<LastLevelRoute, RouteComponent | (() => Promise<{ default: RouteComponent }>)> = {
  "demo-a_child1": () => import("@/views/demo-a/child1/index.vue"),
  "demo-a_child2_child3": () => import("@/views/demo-a/child2/child3/index.vue"),
  "demo-a_child3": () => import("@/views/demo-a/child3/index.vue"),
  demo3: () => import("@/views/demo3/[id].vue"),
};
