/**
 * create the prefix comment of the generated file
 *
 * @param disabledTSCheck whether disabled ts-check
 */
export function createPrefixCommentOfGenFile(disabledTSCheck = false) {
  const prefix = `/* eslint-disable */`;
  let comment = `/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router`;

  if (disabledTSCheck) {
    comment = `// @ts-nocheck\n${comment}`;
  }

  comment = `${prefix}\n${comment}`;

  return comment;
}
