/**
 * create the prefix comment of the generated file
 */
export function createPrefixCommentOfGenFile() {
  return `/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router`;
}
