/* eslint-disable @typescript-eslint/no-unused-vars */
import path from 'path';
import type { RouteRecordRaw } from 'vue-router';
import { loadFile, writeFile, parseModule } from 'magicast';
import type { ElegantRouterFile, ElegantRouterTree } from '@elegant-router/core';
import { createFs } from '../shared/fs';
import type { ElegantVueRouterOption } from '../types';

type AutoRoute = Omit<RouteRecordRaw, 'component' | 'children'> & {
  component?: string;
  children?: AutoRoute[];
};

interface RouteConstExport {
  autoRoutes: AutoRoute[];
}

export async function getConstCode(
  files: ElegantRouterFile[],
  trees: ElegantRouterTree[],
  options: ElegantVueRouterOption
) {
  const { cwd, constDir, splitModule, customRoutesMap } = options;

  const fs = await createFs();

  if (splitModule) {
    // const moduleFilePath = path.join(cwd, dir, ROUTES_MODULE_DIR, ROUTES_FILE_NAME);
  } else {
    const routesFilePath = path.join(cwd, constDir);
    try {
      await fs.ensureFile(routesFilePath);
    } catch {
      createEmptyRouteConst(routesFilePath);
    }

    const md = await loadFile<RouteConstExport>(routesFilePath);
  }
}

async function createEmptyRouteConst(filePath: string) {
  const code = `// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router
import type { RouteRecordRaw } from "vue-router";

export const autoRoutes: RouteRecordRaw[] = [];

`;

  const mod = parseModule<RouteConstExport>(code);

  writeFile({ ast: mod.exports.$ast }, filePath);
}

export function updateRouteConst(oldConst: RouteConstExport, newConst: RouteConstExport) {}

export function getRouteConstExport(trees: ElegantRouterTree[], options: ElegantVueRouterOption) {
  const autoRoutes = trees.map(item => transformRouteTreeToRouteRecordRaw(item, options));

  return { autoRoutes };
}

/**
 * transform ElegantRouter route tree to vue-router route
 * @param tree the ElegantRouter route tree
 * @param options the plugin options
 */
function transformRouteTreeToRouteRecordRaw(tree: ElegantRouterTree, options: ElegantVueRouterOption) {
  const { defaultLayout } = options;
  const { routeName, routePath, children = [] } = tree;

  const firstLevelRoute: AutoRoute = {
    name: routeName,
    path: routePath,
    component: `layouts.${defaultLayout}`,
    meta: {
      key: routeName
    }
  };

  if (children.length === 0) {
    firstLevelRoute.children = [
      {
        path: '.',
        component: `views.${routeName}`,
        meta: {
          key: routeName
        }
      }
    ];

    return firstLevelRoute;
  }

  const routeChildren = children.map(item => recursiveGetRouteRecordRawByChildTree(item));

  firstLevelRoute.children = routeChildren.flat(1);

  return firstLevelRoute;
}

function recursiveGetRouteRecordRawByChildTree(childTree: ElegantRouterTree): AutoRoute[] {
  const { routeName: cName, routePath: cPath, children: cChildren = [] } = childTree;

  const hasChildren = cChildren.length > 0;

  if (!hasChildren) {
    const lastLevelRoute: AutoRoute = {
      name: cName,
      path: cPath,
      component: `views.${cName}`,
      meta: {
        key: cName
      }
    };

    return [lastLevelRoute];
  }

  const [firstChild] = cChildren;

  const autoRoute: AutoRoute = {
    name: cName,
    path: cPath,
    redirect: firstChild.routePath,
    meta: {
      key: cName
    }
  };

  return [autoRoute, ...cChildren.map(item => recursiveGetRouteRecordRawByChildTree(item)).flat(1)];
}

// const importsPath = path.join(cwd, importsDir);
// const routeModulePath = path.join(cwd, moduleDir, `${routeName}.ts`);
// const constPath = path.join(cwd, constDir);

// const componentPath = splitModule
//   ? getRelativeImport(routeModulePath, importsPath)
//   : getRelativeImport(constPath, importsPath);

// export function getRelativeImport(from: string, to: string) {
//   let relativePath = path.relative(path.dirname(from), to);

//   if (!relativePath.startsWith('.')) {
//     relativePath = path.format({ dir: '.', name: relativePath });
//   }

//   const ext = path.extname(relativePath);

//   if (ext) {
//     relativePath = relativePath.replace(ext, '');
//   }

//   return relativePath;
// }
