import path from 'path';
import type { ElegantRouterFile, ElegantRouterNamePathEntry } from '@elegant-router/core';
import type { ElegantVueRouterOption } from '../types';
import { createFs } from '../shared/fs';

function getDtsCode(
  files: ElegantRouterFile[],
  entries: ElegantRouterNamePathEntry[],
  customEntries: ElegantRouterNamePathEntry[]
) {
  const allEntries = [...customEntries, ...entries];

  let code = `/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

declare module "@elegant-router/types" {
  /**
   * route map
   */
  export type RouteMap = {`;
  allEntries.forEach(([routeName, routePath]) => {
    code += `\n    "${routeName}": "${routePath}";`;
  });

  code += `
  };

  /**
   * route key
   */
  export type RouteKey = keyof RouteMap;

  /**
   * custom route key
   */ 
  export type CustomRouteKey = Extract<
    RouteKey,`;

  customEntries.forEach(([routeName]) => {
    code += `\n    | "${routeName}"`;
  });

  code += `
  >;
  
  /**
   * the last level route, which has the page file
   */
  export type LastLevelRoute = Extract<
    RouteKey,`;

  files.forEach(file => {
    code += `\n    | "${file.routeName}"`;
  });

  code += `
  >;
}
`;

  return code;
}

export async function genDtsFile(
  files: ElegantRouterFile[],
  entries: ElegantRouterNamePathEntry[],
  options: ElegantVueRouterOption
) {
  if (files.length === 0) return;

  const fs = await createFs();

  const customEntries = Object.entries(options.customRoutesMap);

  const code = getDtsCode(files, entries, customEntries);

  const dtsPath = path.join(options.cwd, options.dtsDir);

  try {
    await fs.ensureFile(dtsPath);
  } catch {}

  await fs.writeFile(dtsPath, code);
}
