import path from 'path';
import type { ElegantRouterFile } from '@elegant-router/core';
import type { ElegantVueRouterOption } from '../types';
import { createFs } from '../shared/fs';

function getImportsCode(files: ElegantRouterFile[], options: ElegantVueRouterOption) {
  const preCode = `/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router
`;

  let importCode = `\n
import type { RouteComponent } from "vue-router";
import type { LastLevelRoute } from "@elegant-router/types";

`;

  let exportCode = `export const views: Record<LastLevelRoute, RouteComponent | (() => Promise<{ default: RouteComponent }>)> = {`;

  files.forEach(file => {
    const isLazy = options.lazyImport(file.routeName);

    const key = file.routeName.includes('-') ? `"${file.routeName}"` : file.routeName;

    if (isLazy) {
      exportCode += `\n  ${key}: () => import("${file.importPath}"),`;
    } else {
      const importKey = getImportKey(file.routeName);
      importCode += `import ${importKey} from "${file.importPath}";\n`;

      exportCode += `\n  ${key}${key === importKey ? '' : `: ${importKey}`},`;
    }
  });

  exportCode += '\n};\n';

  return `${preCode + importCode}\n${exportCode}`;
}

function getImportKey(name: string) {
  const NUM_REG = /^\d+$/;
  const SHORT_WITH_NUM_OR_CHAR_REG = /-[0-9|a-zA-Z]/g;

  let key = name;

  if (NUM_REG.test(name)) {
    key = `_${name}`;
  }

  key = key.replace(SHORT_WITH_NUM_OR_CHAR_REG, match => {
    let remain = match.replace('-', '').toUpperCase();
    if (NUM_REG.test(remain)) {
      remain = `_${remain}`;
    }
    return remain;
  });

  return key;
}

export async function genImportsFile(files: ElegantRouterFile[], options: ElegantVueRouterOption) {
  if (files.length === 0) return;

  const fs = await createFs();

  const importsPath = path.join(options.cwd, options.importsDir);

  try {
    await fs.ensureFile(importsPath);
  } catch {}

  const code = getImportsCode(files, options);

  await fs.writeFile(importsPath, code);
}
