/* eslint-disable */
/* prettier-ignore */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteFileKey, RouteLayoutKey, RawRouteComponent } from "@elegant-router/types";

export const layouts: Record<RouteLayoutKey, RawRouteComponent> = {
  base: () => import("@/layouts/base/index.vue"),
  blank: () => import("@/layouts/blank/index.vue"),
};

export const views: Record<RouteFileKey, RawRouteComponent> = {
  403: () => import("@/views/(builtin)/403.vue"),
  404: () => import("@/views/(builtin)/404/index.vue"),
  Home: () => import("@/views/home/index.vue"),
  HomeChild: () => import("@/views/home/child.vue"),
  HomeChild5: () => import("@/views/home/child5.vue"),
  List: () => import("@/views/list/index.vue"),
  ListAdd: () => import("@/views/list/add.vue"),
  ListDetail2IdUserId: () => import("@/views/list/detail2-[[id]]-[[userId]].vue"),
  ListDetailIdUserId: () => import("@/views/list/detail_[id]_[userId].vue"),
  ListEditId: () => import("@/views/list/edit_[id].vue"),
  ListId: () => import("@/views/list/[id].vue"),
  Login: () => import("@/views/(builtin)/login/index.vue"),
  Wip: () => import("@/views/(builtin)/wip.vue"),
};
