/* eslint-disable */
/* prettier-ignore */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { AutoRouterRoute } from '@elegant-router/types';

export const routes: AutoRouterRoute[] = [
  {
    name: 'Root',
    path: '/',
    redirect: '/home',
  },
  {
    name: 'NotFound',
    path: '/:pathMatch(.*)*',
    layout: 'blank',
    component: '404',
  },
  {
    name: '403',
    path: '/403',
    layout: 'blank',
    component: '403',
  },
  {
    name: '404',
    path: '/404',
    layout: 'blank',
    component: '404',
  },
  {
    name: 'Demo',
    path: '/demo',
    layout: 'base',
    component: 'Demo',
  },
  {
    name: 'Home',
    path: '/home',
    layout: 'base',
    component: 'Home',
  },
  {
    name: 'HomeChild',
    path: '/home/child',
    layout: 'base',
    component: 'HomeChild',
  },
  {
    name: 'HomeChild5',
    path: '/home/child5',
    layout: 'base',
    component: 'HomeChild5',
  },
  {
    name: 'List',
    path: '/list',
    layout: 'base',
    component: 'List',
  },
  {
    name: 'ListAdd',
    path: '/list/add',
    layout: 'base',
    component: 'ListAdd',
  },
  {
    name: 'ListDetail2IdUserId',
    path: '/list/detail2-:id?-:userId?',
    layout: 'base',
    component: 'ListDetail2IdUserId',
  },
  {
    name: 'ListDetailIdUserId',
    path: '/list/detail/:id/:userId',
    layout: 'base',
    component: 'ListDetailIdUserId',
  },
  {
    name: 'ListEditId',
    path: '/list/edit/:id',
    layout: 'base',
    component: 'ListEditId',
  },
  {
    name: 'ListId',
    path: '/list/:id',
    layout: 'base',
    component: 'ListId',
  },
  {
    name: 'Login',
    path: '/login',
    layout: 'base',
    component: 'Login',
  },
  {
    name: 'Wip',
    path: '/wip',
    layout: 'base',
    component: 'Wip',
  }
];
