/* eslint-disable */
/* prettier-ignore */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteKey, RoutePath, RoutePathMap } from '@elegant-router/types';

const routePathMap: RoutePathMap = {
  "Root": "/",
  "NotFound": "/:pathMatch(.*)*",
  "403": "/403",
  "404": "/404",
  "Demo": "/demo",
  "Home": "/home",
  "HomeChild": "/home/child",
  "HomeChild5": "/home/child5",
  "List": "/list",
  "ListAdd": "/list/add",
  "ListDetail2IdUserId": "/list/detail2-:id?-:userId?",
  "ListDetailIdUserId": "/list/detail/:id/:userId",
  "ListEditId": "/list/edit/:id",
  "ListId": "/list/:id",
  "Login": "/login",
  "Wip": "/wip",
};

export function getRoutePath(key: RouteKey) {
  return routePathMap[key];
}

export function getRouteName(path: RoutePath) {
  return Object.keys(routePathMap).find(key => routePathMap[key as RouteKey] === path) as RouteKey;
}
